[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hisim"
dynamic = ["version"]
description = "A simulation benchmark tool for hicache"
dependencies = [
    "numpy",
    "scikit-learn",
    "xgboost",
    "aiconfigurator @ git+https://github.com/ai-dynamo/aiconfigurator.git@e46ece7510e727fafefb8212e5846172145a30ea",
    "sglang==0.5.9",
    "torch==2.9.1",
]

[dependency-groups]
dev = [
    "pytest>=9.1.0",
]
